[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rayon = "1.10.0"

epaint = { version = "0.30.0", optional = true }
image = { version = "0.25.5", optional = true }

[features]
epaint = ["dep:epaint"]
image = ["dep:image"]